export const GET_USERS = 'GET_USERS';
export const SAVE_USER_QUESTION = 'SAVE_USER_QUESTION';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SAVE_QUESTION = 'SAVE_QUESTION';
export const SAVE_QUESTION_ANSWER = 'SAVE_QUESTION_ANSWER';
export const GET_AUTHED_USER = 'GET_AUTHED_USER';
export const CLEAR_AUTHED_USER = 'CLEAR_AUTHED_USER';
